services:
  jnm-front:
    container_name: jnm2026-front-container
    build:
      context: .
      dockerfile: Dockerfile
    # Mappe le port 3002 de votre machine sur le port 3000 du conteneur
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
    # Redémarre automatiquement le conteneur s'il plante ou si le serveur redémarre
    restart: unless-stopped
    # Optionnel : Limite les ressources pour éviter que Node ne mange toute la RAM
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G